version: "3.7"

networks:
   appnet:

services:
  app-service:
    build: .
    restart: always
    ports: 
      - "9991:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/mydb
      SPRING_DATASOURCE_USERNAME: djs
      SPRING_DATASOURCE_PASSWORD: djs
    depends_on:
      - mysql-service
    networks:
      - appnet

  mysql-service:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: djs
      MYSQL_PASSWORD: djs
      MYSQL_DATABASE: mydb
    networks:
      - appnet